### PR TITLE
2024 08 20/mahir/transaction crud operations

### PR DESCRIPTION
**Pull request by Mahir12746**

### CODE REVIEW

**Review by Mobashir-Monim — COMMENTED** [review]
The `GetTransactions` would be a little more complicated for the search functionality, let's perform pair programming to complete it.

**Comment by Mahir12746** [comment]
GetTransactions Action

Phase 1

For the transaction search action, as you said, the input of the search parameter can be key words related to tags, accounts, revenuestreams, donors and vendors. And the output will be the transactions to be found that have a relation with these domains.

So first step would be to initialize the query builder for transaction
second step could be to import the search actions of the related domains
third step would be to search those related domains
fourth would be to search the transactions related to those domains.

**Comment by Mahir12746** [comment]
GetTransactions Action

Phase 3

Line 1, the php file is opened

Line 3, declaration made that the file will be strictly typed

Line 5, the namespace is App\Domain\Transactions\Actions\Queries meaning that this file can be accessed if we go to App folder then to Domains folder then to Transactions folder and then to Actions folder and then finally to Queries


Line 7, GetAccounts class is imported from App\Domains\Accounts\Actions\Queries\GetAccounts
Line 8, GetDonors class is imported from App\Domains\Donors\Actions\Queries\GetDonors
Line 9, GetTags class is imported from App\Domains\Tags\Actions\Queries\GetTags
Line 10, the transaction model dependency is injected from App\Domains\Transactions\Transaction
Line 11, GetVendors class is imported from App\Domains\Vendors\Actions\Queries\GetVendors
Line 12, the Response dependency is injected from Illuminate\Auth\Access\Response
Line 13, LengthAwarePaginator class is imported from Illuminate\Contracts\Pagination\LengthAwarePaginator
Line 14, Collection class is imported from Illuminate\Support\Collection
Line 15, ActionRequest dependency is injected from Lorisleiva\Actions\ActionRequest
Line 16, AsAction dependency is injected from  Lorisleiva\Actions\Concerns\AsAction

Line 18, the class name is GetTransactions which is also the file name

Line 20, the class is instructed to inherit AsAction which was injected in line 10

Line 22, we have written the authorize function which accepts a HTTP request and the return type is Response model

Line 24, we are getting the user making the request

Line  26, it is being checked whether user has general access or not 
Line 27, if true the response is allowed

Line 30, if not true response is denied with the message "You are unauthorized to perform this action"

Line 33, the handle function is accepting a search term as a string if it is given and a per page value as an integer and the return type of the function is Collection or LengthAwarePaginator

Line 35, transaction query builder is initiated

Line 37, the output of the GetTags search result is stored in $tags variable

Line 39, the output of the GetDonors search result is stored in $donors variable

Line 41, the output of the vendors search result is stored in $vendors variable

Line 43, the output of the GetAccounts search result is stored in $accounts variable

Line 45, if condition checks if search term was given as input for the function or not

Line 46, if given, then using the empty transaction query, the search term is searched in the note column of the transaction table and stored in the query

Line 47, or if the search term matches with the related table tags of the transaction then those tags will be stored
Line 48, the id column of the tags table is being searched for the required tag ids

Line 50, or if the search term matches with the related table donors of the transaction then those donors will be stored
Line 51, the id column of the donors table is being searched for the required donor ids

Line 53, or if the search term matches with the related table vendors of the transaction then those vendors will be stored
Line 54, the id column of the vendors table is being searched for the required vendor ids

Line 56, or if the search term matches with the related table accounts of the transaction then those accounts will be stored
Line 57, the id column of the accounts table is being searched for the required account ids

Line 61, if there is a value given for per_page or there is null is being checked
Line 62, if null all the results will be shown without pagination
Line 63, if value given then pagination will be applied


Line 66, the rules function is written with return type array

Line 69, the search term should be a string and nullable
Line 70, per_page value should be an integer, nullable and there should be at least one number

Line 74, the function asController accepts a HTTP request

Line 76, from the HTTP request the search_term is taken as input or the default value null
Line 77, from the HTTP request the per_page is taken as input or the default value 10

Line 79, the function returns the output of the handle function

Line 82, the jsonResponse function takes input the transactions as array and the HTTP request. Its return type is array.

Line 86, the message variable contains a string

Line 87, in the message variable 'found' will be concatenated if search_term is present or else 'fetched will be concatenated'

Line 90, in the array data as key and $transactions as value is present
Line 91, in the array message as key and "$message . ' successfully'" as value is present

**Comment by Mahir12746** [comment]
GetTransaction Action

Phase 1

Inputs: id as string of the transaction we want to get
Outputs: the desired transaction or null if not found
Logic/Process: finding the transaction with the given id

**Comment by Mahir12746** [comment]
GetTransaction Action

Phase 3

Line 1, the php file is opened

Line 3, declaration made that the file is strictly typed

Line 5, namespace is declared which says the file can be found by going to App folder then to Domains folder then Transactions and then to Actions and then finally to Queries

Line 7, dependency Transaction is injected which can be found from App\Domains\Transactions\Transaction
Line 8, dependency response is injected from Illuminate\Auth\Access\Response
Line 9, dependency ActionRequest is injected from Lorisleiva\Actions\ActionRequest
Line 10, dependency AsAction is injected from Lorisleiva\Actions\Concerns\AsAction

Line 12, class name is written, GetTransaction which is also the file name

Line 14, AsAction is inherited that we injected in line 10

Line 16, a function called authorize is written which is accepting HTTP request and the return type is Response

Line 18, the user variable stores the type of user

Line 20, this if statement checks whether the user has general access or not
Line 21, the if statement returns allowed if true

Line 24, otherwise the function returns denied with a message 'You are unauthorized to perform this action'

Line 27, handle function is written which is accepting id as string and the return type is Transaction model instance or null

Line 29, the function returns the transaction which matches with the given id from the transaction database table

Line 32, rules function is made which has no inputs but has output as an array

Line 35, the function validates the id by mentioning it to be required and that the id exists in the id column of the transactions table

Line 39, asController function is made which accepts HTTP request

Line 41, returns the output of handle function which takes the id of the requested tag from the request

Line 44, jsonResponse function is written which accepts the transaction model instance as the input parameter and the return type is array

Line 47, the function returns an array containing data of transaction
Line 48, and the success message

**Comment by Mahir12746** [comment]
GetTransactions

Phase 1

Input: an integer value for per page data count and a string as search term. Both of them can be null and their default value is 10 and empty string
Output:if value of per page given then data will be paginated and returned otherwise all the data will be returned
Logic/Process: for a specific search term the transaction will be searched if not found then the related domains to transaction will be searched, if found then the related transactions will be returned

Phase 3

Line 1, php file has been opened

Line 3, it is declared that the file will be strictly typed

Line 5, the namespace says where the file is located

Line 9, the GetTags action is being injected from App\Domains\Tags\Actions\Queries\GetTags

Line 11, Transaction model is being injected from App\Domains\Transactions\Transaction

Line 13, Response is being injected from Illuminate\Auth\Access\Response

Line 14, LengthAwarePaginator is being injected from Illuminate\Contracts\Pagination\LengthAwarePaginator
Line 15, Collection is being injected from Illuminate\Support\Collection
Line 16, ActionRequest is being injected from Lorisleiva\Actions\ActionRequest
Line 17, AsAction is being injected from Lorisleiva\Actions\Concerns\AsAction

Line 19, the class name is written which is also the file name

Line 21, AsAction trait is being used 

Line 23, authorize function taking request as input and return type is Response

Line 25, user data from request is being stored in user variable

Line 27, whether user has general access or not is being checked
Line 28, allow method is called from response and is returned

Line 31, if not allowed deny method is called from Response

Line 34, the handle function takes integer value for number of data to be displayed per page and search term as a string. Both of the inputs can be null and their default values are 10 and empty string

Line 36, An empty query of transaction is called

Line 37, tags variable stores the tags found after searching for tags with the search parameter using the GetTags action from the Tags domain

Line 45, if there is  a search term given or not is checked
Line 46, transactions where the search term matches with the note of transaction are stored
Line 47, or the relatable table tags is being searched
Line 48, transactions are stored whose tag id matches with the ids found from the tag search

Line 61, whether per_page is null or not being checked
Line 62, if null all the transaction data are being returned
Line 63, or transactions are paginated using per_page and then returned

Line 66, the rules method without input is written the return type is array

Line 69, the search_term is validated so that input must be string and can be nullable
Line 70, per_page must be integer with minimum value that can be is 1 and can be nulllable 

Line 74, asController function is called with the request being as input

Line 76, the handle function from this file with perpage and searchterm as parameter is being returned

Line 79, function jsonResponse is written
Line 80, the transaction and request are passed as parameter with their type being Collection | LengthAwarePaginator and ActionRequest the return type is array

Line 83, a message variable contains the transaction count

Line 88, the message is being returned

**Comment by Mahir12746** [comment]
GetTransactions

Phase 1

Input: an integer value for per page data count and a string as search term. Both of them can be null and their default value is 10 and empty string
Output:if value of per page given then data will be paginated and returned otherwise all the data will be returned as a collection.
Logic/Process: for a specific search term the transaction will be searched if not found then the related domains to transaction will be searched, if found then the related transactions will be returned

Phase 3

Line 1, php file has been opened

Line 3, it is declared that the file will be strictly typed

Line 5, the namespace says where the file is located

Line 7, Account model is being injected from App\Domains\Accounts\Account
Line 8, GetAccounts action is being injected from App\Domains\Accounts\Actions\Queries\GetAccounts
Line 9, Donor model is being injected from App\Domains\Donors\Donor
Line 10, GetDonors action is being injected from App\Domains\Donors\Actions\Queries\GetDonors
Line 11, Employee model is being injected from App\Domains\Employees\Employee
Line 12, GetEmployees action is being injected from App\Domains\Employees\Actions\Queries\GetEmployees
Line 13, RevenueStream model is being injected from App\Domains\RevenueStreams\RevenueStream
Line 14, GetRevenueStreams action is being injected from App\Domains\RevenueStreams\Actions\Queries\GetRevenueStreams
Line 15, GetTags action is being injected from App\Domains\Tags\Actions\Queries\GetTags
Line 16, Transaction model is being injected from App\Domains\Transactions\Transaction
Line 17, GetUsers  action can be injected from App\Domains\Users\Actions\Queries\GetUsers
Line 18, Vendor model is being injected from App\Domains\Vendors\Vendor
Line 19, GetVendors action is being injected from App\Domains\Vendors\Actions\Queries\GetVendors
Line 20, Response is being injected from Illuminate\Auth\Access\Response
Line 21, LengthAwarePaginator is being injected from Illuminate\Contracts\Pagination\LengthAwarePaginator
Line 22, Collection is being injected from Illuminate\Support\Collection
Line 23, ActionRequest HTTP request is being injected from Lorisleiva\Actions\ActionRequest
Line 24, AsAction is being injected from Lorisleiva\Actions\Concerns\AsAction

Line 26, it is the name of the class which is also the name of the file

Line 28, AsAction trait being used which was injected in line 24

Line 30, the authorize function takes request as input and return type is response

Line 32, user variable stores the data about the user making the request

Line 34, if user has general access or not is being checked
Line 35, if true then allow method from response is being called and returned

Line 38, otherwise deny method is being called from response which is then returned

Line 41, handle function is written
Line 42, default value of per_page is 10 and it can also accept null
Line 43, default value of search_term is empty string and it can also accept null
Line 44, the return type is is either collection or lengthawarepaginator

Line 46, a empty transaction query is made
Line 47, the GetTags action is being called using the static run method by passing per_page and search_term as parameters
Line 48, the GetUsers action is being called using the static run method by passing per_page and search_term as parameters
Line 49, the GetAccounts action is being called using the static run method by passing per_page and search_term as parameters
Line 50, the GetDonors action is being called using the static run method by passing per_page and search_term as parameters
Line 51, the GetVendors action is being called using the static run method by passing per_page and search_term as parameters
Line 52, the GetEmployeess action is being called using the static run method by passing per_page and search_term as parameters
Line 53, the GetRevenueStreams action is being called using the static run method by passing per_page and search_term as parameters

Line 55, if statement checks whether search term given or not

Line 56, using the transaction query the note column is searched with the search term
Line 57, orWhereIn is used to compare the author_id column from the transaction table with the ids plucked from users if any
Line 58, the id of the transactions from the transaction table are being compared with a query written in closure
Line 59, a query is written to select transaction_id
Line 60, from the tag_transaction table
Line 61, where tag_id column in that table matches with the plucked id from tags

Line 63, the orWhereHasMorph method takes morph relation type, the class name of the related domain and a closure
Line 64, in the closure a query is made which compares the fromable ids with the plucked ids from accounts

Line 66, the orWhereHasMorph method takes morph relation type, the class name of the related domain and a closure
Line 67, in the closure a query is made which compares the fromable ids with the plucked ids from donors

Line 69, the orWhereHasMorph method takes morph relation type, the class name of the related domain and a closure
Line 70, in the closure a query is made which compares the fromable ids with the plucked ids from revenue_streams

Line 72, the orWhereHasMorph method takes morph relation type, the class name of the related domain and a closure
Line 73, in the closure a query is made which compares the toable ids with the plucked ids from accounts

Line 75, the orWhereHasMorph method takes morph relation type, the class name of the related domain and a closure
Line 76, in the closure a query is made which compares the toable ids with the plucked ids from vendors

Line 78, the orWhereHasMorph method takes morph relation type, the class name of the related domain and a closure
Line 79, in the closure a query is made which compares the toable ids with the plucked ids from employees

Line 83, the method will return all the transactions without pagination if per_page is null

Line 85, otherwise pagination will be applied and then returned

Line 88, the rules method takes no input and the return type is array

Line 91, a array is being returned where the search term is validated by stating it can be nullable and must be a string
Line 92, the per_page is being validated by stating it can be nullable integer and minimum numeric value must be 1

Line 96, asController method is written taking request as input

Line 98, the method returns the output of the handle method by passing the per_page and search_term from the request into the handle

Line 101, jsonResponse function is written
Line 102, the function takes transactions and request as parameters

Line 106, message variable stores the count of the transactions
Line 107, from the request whether the search_term was given or not was checked to concatenate found if true otherwise fetched in message

Line 110, the transactions are returned along with the message

**Review by Mobashir-Monim — APPROVED** [review]

**Pull request merged**
